import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from '@react-oauth/google';
import Script from 'next/script'

export const metadata = {
  title: "Artists Like Ourselves",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head> 
      </head>
      <body  style={{backgroundColor: 'rgba(0, 0, 0, 0.1)', overflowX: 'hidden!important'}} className={inter.className}>
        <div id="fb-root">
          <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID}>
            <Toaster  position="bottom-center" 
              toastOptions={{
                className: '',
                style: {
                  backgroundColor: 'black',
                  padding: '8px',
                  color: 'white',
                },
              }}
            />

            {children}
          </GoogleOAuthProvider>
        </div>
      </body>
    </html>
  );
}
